# Site settings
title:          lazySquare
description:    "lazy^2 developer's blog"
url:            https://lazymonday.github.io

# Author
author:
  name:         Sangjoon Lee
  email:        lazymonday@gmail.com
  url:          https://lazymonday.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: lazymonday@gmail.com
  github: https://github.com/lazymonday
  twitter: https://twitter.com
  linkedin: https://linked.in
